---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
      - name: login-app
        image: honeyy02/login-python:latest  # Replace with your Docker image
        ports:
        - containerPort: 5000
        env:
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: login-app-config
              key: USERNAME
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: login-app-secret
              key: SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: login-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: login-app
