apiVersion: v1
kind: ConfigMap
metadata:
  name: login-app-config
data:
  USERNAME: "admin"  # Non-sensitive configuration
---
apiVersion: v1
kind: Secret
metadata:
  name: login-app-secret
type: Opaque
data:
  SECRET_KEY: cGFzc3dvcmQ=  # Base64 encoded 'password'
